NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
HORIZON_URL="https://horizon.stellar.org"
ACCOUNTS=[
"GBJGR7HDC4QPCZ6SA5VBH73V7L5SSZ5GAS6US23PFSGV4SQXJLYGERYX",
"GBLR4DA5XASK5FQZ2ENSU6LMMO5PGERDEH64Q2R2PQQUTJPQW4VF2ZFS"
]


[[CURRENCIES]]
code="RUV"
issuer="GBJGR7HDC4QPCZ6SA5VBH73V7L5SSZ5GAS6US23PFSGV4SQXJLYGERYX"
status="live"
display_decimals=8
name="RuvChain"
fixed_number=1000000000
desc="RuvChain is a digital token to the Stellar Blockchain.RuvChain is an open source blockchain platform, RUV is proof that, blockchain technology is not only about simple transfer of value but also has the potential to revolutionize many aspects of our lives with the various decentralized applications that can be built with it."
conditions="There will only ever be 1000,000,000 RUV tokens in existence."
image="https://www.ruvcha.in/img/logo.png"

[DOCUMENTATION]
ORG_NAME="RuvChain"
ORG_URL="https://www.ruvcha.in"
ORG_LOGO="https://www.ruvcha.in/img/logo.png"
ORG_DESCRIPTION="RuvChain is a digital token to the Stellar Blockchain.RuvChain is an open source blockchain platform, RUV is proof that, blockchain technology is not only about simple transfer of value but also has the potential to revolutionize many aspects of our lives with the various decentralized applications that can be built with it."
ORG_OFFICIAL_EMAIL="admin@ruvcha.in"
ORG_TWITTER="ruvchain"
ORG_GITHUB="ruvchain"
ORG_KEYBASE="ruvcoindev"


[[PRINCIPALS]]
name="Vitaly Prigorko"
email="admin@ruvcha.in"
keybase="ruvcoindev"
twitter="ruvchain"
github="ruvchain"
